language: ruby
rvm:
  - 2.0.0
env:
  global:
    - DB=mysql
    - TRAVIS=true
branches:
  only:
    - 'master'
    - 'develop'
services:
  - mysql
  - redis-server
before_script:
  - "cp config/database.yml.example config/database.yml"
  - "cp config/gitlatex.yml.example config/gitlatex.yml"
  - "bundle exec rake db:setup"
  - "bundle exec rake db:seed_fu"
script: "bundle exec rake $TASK --trace"
